version: '3.8'
services:
  postgres:
    env_file:
    - .env
    image: postgres:14-alpine
    restart: always 
    #container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always 
    #container_name: web_app
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    command: npm start --host 0.0.0.0
    depends_on:
      - postgres

volumes:
  postgres-data:
  node_modules: